# Generated by Django 5.1.5 on 2025-02-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=200)),
                ("bio", models.TextField()),
                ("education", models.TextField()),
                ("skills", models.TextField()),
                ("experience", models.TextField()),
                ("projects", models.TextField()),
                ("extracurricular", models.TextField()),
            ],
        ),
    ]
